# Netlify config for Next.js (App Router, API routes, Edge/SSR)

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  included_files = ["public/**"]

# ✅ Plugins must use the array-of-tables syntax:
[[plugins]]
  package = "@netlify/plugin-nextjs"
